version: '2'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/data
    ports: 
      - "3308:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD: testes"
      - "MYSQL_USER: root"
      - "MYSQL_DATABASE: user_admin"
      
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data

  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php
    depends_on:
      - redis
      - mysql
    command: bash -c "sh crontab-install.sh && php-fpm  && php-fpm -v"
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_PORT=3308"
      - "DB_USERNAME=root"
      - "DB_DATABASE=user_admin"
      - "DB_PASSWORD=testes"
      - "MYSQL_HOST=mysql"
      - "REDIS_HOST=redis"
      - "DEBUG=true"
      
    links:
      - mysql:mysql
    volumes:
      - ./app/:/var/www/html:rw

  web:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 4001:4001

volumes:
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"